[Settings]
  ID = "34ae802e-fb42-4bab-8814-9fac9e119037"

[Build]
  base = "/"
  publish = "docs/_site/"
  command = "grunt deploy-docs"

[[redirects]]
  from = "/product"
  to = "/product/guidelines/using-stacks/"

[[redirects]]
  from = "/email"
  to = "/email/guidelines/getting-started"

[[redirects]]
  from = "/content"
  to = "/content/guidelines/principles"

[[redirects]]
  from = "/brand"
  to = "/brand/principles"

[[redirects]]
  from = "/product/guidelines"
  to = "/product/guidelines/using-stacks"

[[redirects]]
  from = "/email/guidelines"
  to = "/email/guidelines/getting-started"

[[redirects]]
  from = "/email/guidelines/best-practices"
  to = "/email/guidelines/design-best-practices"

[[redirects]]
  from = "/guidelines/using-stacks"
  to = "/product/guidelines/using-stacks"

[[redirects]]
  from = "/guidelines/customization"
  to = "/product/guidelines/customization"

[[redirects]]
  from = "/guidelines/responsiveness"
  to = "/product/guidelines/responsiveness"

[[redirects]]
  from = "/resources/icons"
  to = "/product/resources/icons"

[[redirects]]
  from = "/base/borders"
  to = "/product/base/borders"

[[redirects]]
  from = "/base/box-shadow"
  to = "/product/base/box-shadow"

[[redirects]]
  from = "/base/box-sizing"
  to = "/product/base/box-sizing"

[[redirects]]
  from = "/base/colors"
  to = "/product/base/colors"

[[redirects]]
  from = "/base/cursors"
  to = "/product/base/cursors"

[[redirects]]
  from = "/base/display"
  to = "/product/base/display"

[[redirects]]
  from = "/base/floats"
  to = "/product/base/floats"

[[redirects]]
  from = "/base/grid"
  to = "/product/base/grid"

[[redirects]]
  from = "/base/opacity"
  to = "/product/base/opacity"

[[redirects]]
  from = "/base/overflow"
  to = "/product/base/overflow"

[[redirects]]
  from = "/base/pointer-events"
  to = "/product/base/pointer-events"

[[redirects]]
  from = "/base/position"
  to = "/product/base/position"

[[redirects]]
  from = "/base/spacing"
  to = "/product/base/spacing"

[[redirects]]
  from = "/base/typography"
  to = "/product/base/typography"

[[redirects]]
  from = "/base/vertical-alignment"
  to = "/product/base/vertical-alignment"

[[redirects]]
  from = "/base/width-height"
  to = "/product/base/width-height"

[[redirects]]
  from = "/base/z-index"
  to = "/product/base/z-index"

[[redirects]]
  from = "/components/avatars"
  to = "/product/components/avatars"

[[redirects]]
  from = "/components/badges"
  to = "/product/components/badges"

[[redirects]]
  from = "/components/banners"
  to = "/product/components/banners"

[[redirects]]
  from = "/components/buttons"
  to = "/product/components/buttons"

[[redirects]]
  from = "/components/button-groups"
  to = "/product/components/button-groups"

[[redirects]]
  from = "/components/cards"
  to = "/product/components/cards"

[[redirects]]
  from = "/components/checkbox"
  to = "/product/components/checkbox"

[[redirects]]
  from = "/components/inputs"
  to = "/product/components/inputs"

[[redirects]]
  from = "/components/labels"
  to = "/product/components/labels"

[[redirects]]
  from = "/components/links"
  to = "/product/components/links"

[[redirects]]
  from = "/components/modals"
  to = "/product/components/modals"

[[redirects]]
  from = "/components/notices"
  to = "/product/components/notices"

[[redirects]]
  from = "/components/progress-bars"
  to = "/product/components/progress-bars"

[[redirects]]
  from = "components/radio"
  to = "/product/components/radio"

[[redirects]]
  from = "/components/select"
  to = "/product/components/select"

[[redirects]]
  from = "components/sidebar-widgets"
  to = "/product/components/sidebar-widgets"

[[redirects]]
  from = "/components/tables"
  to = "/product/components/tables"

[[redirects]]
  from = "/components/tags"
  to = "/product/components/tags"

[[redirects]]
  from = "/components/textarea"
  to = "/product/components/textarea"

[[redirects]]
  from = "/product/guidelines/responsiveness"
  to = "/product/guidelines/conditional-classes"

[[redirects]]
  from = "/product/base/pointer-events"
  to = "/product/base/interactivity"

[[redirects]]
  from = "/content/principles"
  to = "/content/guidelines/principles"

[[redirects]]
  from = "/content/voice-and-tone"
  to = "/content/guidelines/voice-and-tone"

[[redirects]]
  from = "/content/grammar-and-mechanics"
  to = "/content/guidelines/grammar-and-mechanics"

[[redirects]]
  from = "/assets/img/logo-stacks@2x.png"
  to = "/assets/img/logos/so/logo-stacks@2x.png"