- section: Constants
  options: true
  variables:
    - variable: "@css-reset"
      default: normalize
      options: normalize, meyer, none
      description: Which CSS reset to compile in. Legal values are <code class="stacks-code">normalize</code> for Nicolas Gallagher's normalize.css, <code class="stacks-code">meyer</code> for the Eric Meyer reset, and <code class="stacks-code">none</code> if no CSS reset should be compiled in.
    - variable: "@breakpoints"
      default: 1264px, 980px, 640px
      options: User defined
      description: One or multiple groups of width breakpoints that allow customization of the responsive classes that are generated, including the possibility to apply different breakpoints based on additional selectors (e.g. CSS class on the root element). See the <a href="https://github.com/StackExchange/Stacks/blob/master/lib/css/base/_stacks-configuration-static.less#L14">code comments</a> for details.
- section: Background color
  options: false
  variables:
    - variable: "@bgc-lightest"
      default: "@black-050"
      description: The lightest gray <code class="stacks-code">background-color</code>.
    - variable: "@bgc-lighter"
      default: "@black-075"
      description: A lighter gray <code class="stacks-code">background-color</code>.
    - variable: "@bgc-light"
      default: "@black-100"
      description: A light gray <code class="stacks-code">background-color</code>.
    - variable: "@bgc-darkest"
      default: "@black-350"
      description: The darkest gray <code class="stacks-code">background-color</code>.
    - variable: "@bgc-darker"
      default: "@black-300"
      description: A darker gray <code class="stacks-code">background-color</code>.
    - variable: "@bgc-dark"
      default: "@black-200"
      description: A dark gray <code class="stacks-code">background-color</code>.
- section: Badge colors
  options: false
  variables:
    - variable: "@badge-gold"
      default: "#FFCC01"
      description:
    - variable: "@badge-silver"
      default: "#B4B8BC"
      description:
    - variable: "@badge-bronze"
      default: "#D1A684"
      description:
- section: Border color
  options: false
  variables:
    - variable: "@brc-lightest"
      default: "@black-050"
      description: The lightest gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-lighter"
      default: "@black-075"
      description: A lighter gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-light"
      default: "@black-100"
      description: A light gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-darkest"
      default: "@black-350"
      description: The darkest gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-darker"
      default: "@black-300"
      description: A darker gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-dark"
      default: "@black-200"
      description: A dark gray <code class="stacks-code">border-color</code>.
    - variable: "@brc-orange"
      default: "@orange-400"
      description: An orange <code class="stacks-code">border-color</code>.
- section: Border radius
  options: false
  variables:
    - variable: "@br-sm"
      default: "3px"
      description:
    - variable: "@br-md"
      default: "5px"
      description:
    - variable: "@br-lg"
      default: "7px"
      description:
    - variable: "@br-circle"
      default: "50%"
      description:
- section: Box shadow
  options: false
  variables:
    - variable: "@bs-sm"
      default: "0 @su2 @su8 fade(@black-700, 10%)"
      description:
    - variable: "@bs-md"
      default: "0 @su4 @su8 fade(@black-700, 20%)"
      description:
    - variable: "@bs-lg"
      default: "0 @su4 @su12 fade(@black-800, 20%)"
      description:
    - variable: "@bs-i-sm"
      default: "inset 0 @su2/2 @su8 0 fade(@black-700, 10%)"
      description:
    - variable: "@bs-i-md"
      default: "inset 0 @su2/2 @su8 0 fade(@black-700, 20%)"
      description:
    - variable: "@bs-i-lg"
      default: "inset 0 @su2/2 @su12 0 fade(@black-800, 20%)"
      description:
- section: Code colors
  options: false
  variables:
    - variable: "@code-black"
      default: "#303336"
      description:
    - variable: "@code-gray"
      default: "#858C93"
      description:
    - variable: "@code-blue"
      default: "#0F74BD"
      description:
    - variable: "@code-maroon"
      default: "#7D2727"
      description:
    - variable: "@code-purple"
      default: "#101094"
      description:
    - variable: "@code-teal"
      default: "#2B91AF"
      description:
    - variable: "@code-red"
      default: "#E64320"
      description:
- section: Font color
  options: false
  variables:
    - variable: "@fc-light"
      default: "@black-500"
      description: Light gray font color
    - variable: "@fc-medium"
      default: "@black-700"
      description: Medium gray font color
    - variable: "@fc-dark"
      default: "@black-900"
      description: Dark gray font color
- section: Font family
  options: false
  variables:
    - variable: "@ff-sans"
      default: "Arial, \"Helvetica Neue\", Helvetica, sans-serif"
      description: Sets the sans-serif font stack.
    - variable: "@ff-serif"
      default: "Georgia, Times New Roman, Times, serif"
      description: Sets the serif font stack.
    - variable: "@ff-mono"
      default: "Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, sans-serif"
      description: Sets the monospace font stack.
- section: Font sizes
  options: false
  variables:
    - variable: "@fs-base"
      default: "@fs-body1"
      description: Sets the body <code class="stacks-code">font-size</code>. Default size is <code class="stacks-code">13px</code>.
    - variable: "@fs-fine"
      default: "11px"
      description:
    - variable: "@fs-caption"
      default: "12px"
      description:
    - variable: "@fs-body1"
      default: "13px"
      description:
    - variable: "@fs-body2"
      default: "15px"
      description:
    - variable: "@fs-body3"
      default: "17px"
      description:
    - variable: "@fs-subheading"
      default: "19px"
      description:
    - variable: "@fs-title"
      default: "21px"
      description:
    - variable: "@fs-headline1"
      default: "27px"
      description:
    - variable: "@fs-headline2"
      default: "34px"
      description:
    - variable: "@fs-display1"
      default: "43px"
      description:
    - variable: "@fs-display2"
      default: "55px"
      description:
    - variable: "@fs-display3"
      default: "69px"
      description:
    - variable: "@fs-display4"
      default: "99px"
      description:
- section: Line height
  options: false
  variables:
    - variable: "@lh-base"
      default: "@lh-md"
      description: Sets the universal line-height value.
    - variable: "@lh-xs"
      default: "1"
      description:
    - variable: "@lh-sm"
      default: "(unit(@fs-base) + 2) / unit(@fs-base)"
      description:
    - variable: "@lh-md"
      default: "(unit(@fs-base) + 4) / unit(@fs-base)"
      description:
    - variable: "@lh-lg"
      default: "(unit(@fs-base) + 8) / unit(@fs-base)"
      description:
    - variable: "@lh-xl"
      default: "(unit(@fs-base) + 12) / unit(@fs-base)"
      description:
    - variable: "@lh-xxl"
      default: "2"
      description:
- section: Spacing units
  options: false
  variables:
    - variable: "@s-full"
      default: "97.2307692rem"
      description: Used for responsive design
    - variable: "@s-step"
      default: "@s-full / 12"
      description: Used for responsive design
    - variable: "@su2"
      default: "2px"
      description:
    - variable: "@su4"
      default: "4px"
      description:
    - variable: "@su8"
      default: "8px"
      description:
    - variable: "@su12"
      default: "12px"
      description:
    - variable: "@su16"
      default: "16px"
      description:
    - variable: "@su24"
      default: "24px"
      description:
    - variable: "@su32"
      default: "32px"
      description:
    - variable: "@su48"
      default: "48px"
      description:
    - variable: "@su64"
      default: "64px"
      description:
- section: Transition easings
  options: false
  variables:
    - variable: "@te-smooth-slow"
      default: "cubic-bezier(0.25, 0.46, 0.45, 0.94)"
      description: Uses the <a href="https://easings.net/#easeOutQuad">easeOutQuad easing</a>.
    - variable: "@te-smooth"
      default: "cubic-bezier(0.165, 0.84, 0.44, 1)"
      description: Uses the <a href="https://easings.net/#easeOutQuart">easeOutQuart easing</a>.
    - variable: "@te-smooth-quick"
      default: "cubic-bezier(0.19, 1, 0.22, 1)"
      description: Uses the <a href="https://easings.net/#easeOutExpo">easeOutExpo easing</a>.
    - variable: "@te-back-out"
      default: "cubic-bezier(0.175, 0.885, 0.32, 1.275)"
      description: Uses the <a href="https://easings.net/#easeOutBack">easeOutBack easing</a>.
    - variable: "@te-back-slow"
      default: "cubic-bezier(0.68, -0.55, 0.265, 1.55)"
      description: Uses the <a href="https://easings.net/#easeInOutBack">easeInOutBack easing</a>.
- section: Z-Index
  options: false
  variables:
    - variable: "@zi-hide"
      default: "-1"
      description: Hides element behind all other elements.
    - variable: "@zi-base"
      default: "0"
      description: Reset <code class="stacks-code">z-index</code> to 0.
    - variable: "@zi-selected"
      default: "25"
      description: Pop the element above siblings.
    - variable: "@zi-active"
      default: "30"
      description: Pop above selected siblings.
    - variable: "@zi-navigation"
      default: "1000"
      description: Set the <code class="stacks-code">z-index</code> value for navigation.
    - variable: "@zi-navigation-fixed"
      default: "1050"
      description: Set the <code class="stacks-code">z-index</code> value for fixed navigation bars.
    - variable: "@zi-dropdown"
      default: "2000"
      description: Set the <code class="stacks-code">z-index</code> value for dropdowns.
    - variable: "@zi-popovers"
      default: "3000"
      description: Set the <code class="stacks-code">z-index</code> value for popovers.
    - variable: "@zi-tooltips"
      default: "4000"
      description: Set the <code class="stacks-code">z-index</code> value for tooltips.
    - variable: "@zi-banners"
      default: "5000"
      description: Set the <code class="stacks-code">z-index</code> value for banners.
    - variable: "@zi-modals"
      default: "9000"
      description: Set the <code class="stacks-code">z-index</code> value for modals.
    - variable: "@zi-modals-background"
      default: "@zi-modals - 50"
      description: Set the <code class="stacks-code">z-index</code> value for modal backgrounds.
